wget -O - https://raw.githubusercontent.com/macductan/script_setup_ubuntu/main/package.sh | sh
wget -O - https://raw.githubusercontent.com/macductan/script_setup_ubuntu/main/zsh.sh | sh
wget -O - https://raw.githubusercontent.com/macductan/script_setup_ubuntu/main/flameshot.sh | sh
wget -O - https://raw.githubusercontent.com/macductan/script_setup_ubuntu/main/diodon.sh | sh
wget -O - https://raw.githubusercontent.com/macductan/script_setup_ubuntu/main/nvm.sh | sh
wget -O - https://raw.githubusercontent.com/macductan/script_setup_ubuntu/main/docker.sh | sh
wget -O - https://raw.githubusercontent.com/macductan/script_setup_ubuntu/main/bamboo-key.sh | sh
wget -O - https://raw.githubusercontent.com/macductan/script_setup_ubuntu/main/postman.sh | sh
wget -O - https://raw.githubusercontent.com/macductan/script_setup_ubuntu/main/indicator-multiload.sh | sh
